### ISSUE TITLE
chore: Sync labels

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/github#2]
from https://github.com/Decenter-AI/test/labels

Create new labels in 

- [x] https://github.com/DeCenter-AI/app.decenterai.com/  @RedValis
- [x] https://github.com/DeCenter-AI/decenterai.com/  @RedValis 
- [x] https://github.com/DeCenter-AI/decenter-ai.streamlit.app/ @RedValis 
- [x]  https://github.com/DeCenter-AI/github @RedValis

**Comment by RedValis** [comment]
New labels all added

**Comment by Nasfame** [comment]
@RedValis can u add it for the rest 2 repos as well

**Comment by RedValis** [comment]
> @RedValis can u add it for the rest 2 repos as well

Sure, I'll do it

**Comment by RedValis** [comment]
All done, closing issue

**Comment by Nasfame** [comment]
@RedValis good job
